service:
  name: osu-dx-mcm-${opt:stage, 'development'}

package:
  individually: true
  exclude:
    - .git/**

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-west-2'}
  stackName: ${self:service.name}
  deploymentBucket:
    name: osu-dx-mcm-deployments
    blockPublicAccess: true
  deploymentPrefix: ${self:service.name}
  environment:
    ENV: ${opt:stage, 'development'}
  tracing: ${file(./serverless.config.${opt:stage, 'development'}.yml):provider.tracing}
  apiKeys: ${file(./serverless.config.${opt:stage, 'development'}.yml):provider.apiKeys}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: !Ref apiSnsTopic
  apiGateway:
    apiKeySourceType: HEADER
  usagePlan: ${file(./serverless.config.${opt:stage, 'development'}.yml):provider.usagePlan}

functions:
  - ${file(./src/api/serverless-functions.yml)}
  - ${file(./src/listener/serverless-functions.yml)}

resources: ${file(./serverless-resources.yml)}
