service:
  name: dx-mcm

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt: [receiverQueue, Arn]

functions:
  sender:
    handler: src/sender.handler
    environment:
      SQS_AWS_ACCOUNT_ID: ${file(config.${self:provider.stage}.json):SQS_AWS_ACCOUNT_ID}
      SQS_HOST: ${file(config.${self:provider.stage}.json):SQS_HOST}
      SQS_QUEUE_NAME: ${file(config.${self:provider.stage}.json):SQS_QUEUE_NAME}
    events:
      - http:
          method: post
          path: sender

  receiver:
    handler: src/receiver.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - receiverQueue
              - Arn
resources:
  Resources:
    receiverQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: receiverQueue
