service:
  name: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-infrastructure

plugins:
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters
  - serverless-plugin-stack-outputs

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-west-2'}
  stackName: ${self:service.name}

resources:
  Resources:
    messagesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-Messages
        AttributeDefinitions:
          - AttributeName: sendAt
            AttributeType: S
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: hash
            AttributeType: S
        KeySchema:
          - AttributeName: sendAt
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        GlobalSecondaryIndexes:
          - IndexName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-MessageStatuses
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: sendAt
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - id
              ProjectionType: INCLUDE
          - IndexName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-MessageByHash
            KeySchema:
              - AttributeName: hash
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - id
          - IndexName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-MessageId
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    userMessagesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-UserMessages
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: channelMessageId
            AttributeType: S
          - AttributeName: sendAt
            AttributeType: S
          - AttributeName: channelDeliveredAt
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: channelMessageId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        LocalSecondaryIndexes:
          - IndexName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-UserMessageByChannel
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: channelDeliveredAt
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - sendAt
                - status
                - channelDeliveredAt
          - IndexName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-UserMessageBySendAt
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: sendAt
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - channelMessageId
        GlobalSecondaryIndexes:
          - IndexName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-UserMessageByStatus
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: status
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - channelMessageId

    userMessagesPendingTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-UserMessagesPending
        AttributeDefinitions:
          - AttributeName: status
            AttributeType: S
          - AttributeName: messageChannelUser
            AttributeType: S
          - AttributeName: updatedAtMessageId
            AttributeType: S
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: messageChannelUser
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        LocalSecondaryIndexes:
          - IndexName: osu-dx-mcm-${opt:stage, 'development'}${file(./src/serverless.js):developerSuffix}-UserMessagePendingUpdatedAt
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: updatedAtMessageId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

  Outputs:
    MessagesTable:
      Description: Messages table arn
      Value: !GetAtt messagesTable.Arn
    UserMessagesTable:
      Description: UserMessages table arn
      Value: !GetAtt userMessagesTable.Arn
    UserMessagesPendingTable:
      Description: UserMessagesPending table arn
      Value: !GetAtt userMessagesPendingTable.Arn
