service:
  name: osu-dx-mcm-${opt:stage, 'development'}${opt:developer, ''}
  description: OSU DX Multi-Channel Messaging Stack

package:
  individually: true
  exclude:
    - .git/**

plugins:
  - serverless-dotenv-plugin
  - serverless-s3-sync
  - serverless-pseudo-parameters
  - serverless-step-functions
  - serverless-webpack

custom: ${file(./serverless-custom.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-west-2'}
  stackName: ${self:service.name}
  deploymentBucket:
    name: osu-dx-mcm-deployments
    blockPublicAccess: true
  deploymentPrefix: ${self:service.name}
  environment:
    ENV: ${env:ENV}
    SERVICE_NAME: ${self:service.name}
  apiKeys:
    - ${self:service.name}-${env:AWS_APIGW_API_KEY}
  tracing: ${file(./serverless.config.${opt:stage, 'development'}.yml):provider.tracing}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: !Ref apiSnsTopic
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - !GetAtt messagesTable.Arn
        - !Join ['', [!GetAtt messagesTable.Arn, '/index/${self:service.name}-MessageStatuses']]
        - !GetAtt userMessagesTable.Arn
        - !Join [
            '',
            [!GetAtt userMessagesTable.Arn, '/index/${self:service.name}-UserMessageStatuses'],
          ]
        - !Join [
            '',
            [!GetAtt userMessagesTable.Arn, '/index/${self:service.name}-UserMessageChannels'],
          ]
        - !Join [
            '',
            [!GetAtt userMessagesTable.Arn, '/index/${self:service.name}-UserMessageSendAt'],
          ]
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
        - sqs:DeleteMessage
        - sqs:ReceiveMessage
        - sqs:GetQueueAttributes
      Resource:
        - !GetAtt messagesSqsQueue.Arn
        - !GetAtt userMessagesSqsQueue.Arn
    - Effect: Allow
      Action:
        - logs:CreateLogDelivery
        - logs:GetLogDelivery
        - logs:UpdateLogDelivery
        - logs:DeleteLogDelivery
        - logs:ListLogDeliveries
        - logs:PutResourcePolicy
        - logs:DescribeResourcePolicies
        - logs:DescribeLogGroups
        - states:StartExecution
      Resource:
        - !Join [':', ['arn:aws:states', !Ref AWS::Region, !Ref AWS::AccountId, 'stateMachine:*']]

  apiGateway:
    apiKeySourceType: HEADER
  usagePlan: ${file(./serverless.config.${opt:stage, 'development'}.yml):provider.usagePlan}

stepFunctions:
  stateMachines:
    messageStateMachine: ${file(./src/services/messages/serverless-state-machine.yml)}

functions:
  - ${file(./src/services/messages/serverless-functions.yml)}
  - ${file(./src/services/userMessages/serverless-functions.yml)}

resources: ${file(./serverless-resources.yml)}
