messagesTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: ${self:service.name}-Messages
    AttributeDefinitions:
      - AttributeName: sendAt
        AttributeType: S
      - AttributeName: id
        AttributeType: S
      - AttributeName: status
        AttributeType: S
      - AttributeName: hash
        AttributeType: S
    KeySchema:
      - AttributeName: sendAt
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    GlobalSecondaryIndexes:
      - IndexName: ${self:service.name}-MessageStatuses
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: sendAt
            KeyType: RANGE
        Projection:
          NonKeyAttributes:
            - id
          ProjectionType: INCLUDE
      - IndexName: ${self:service.name}-MessageByHash
        KeySchema:
          - AttributeName: hash
            KeyType: HASH
        Projection:
          ProjectionType: INCLUDE
          NonKeyAttributes:
            - id
      - IndexName: ${self:service.name}-MessageId
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        Projection:
          ProjectionType: ALL

userMessagesTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: ${self:service.name}-UserMessages
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: channelMessageId
        AttributeType: S
      - AttributeName: sendAt
        AttributeType: S
      - AttributeName: channelDeliveredAt
        AttributeType: S
      - AttributeName: status
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: channelMessageId
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    LocalSecondaryIndexes:
      - IndexName: ${self:service.name}-UserMessageByChannel
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: channelDeliveredAt
            KeyType: RANGE
        Projection:
          ProjectionType: INCLUDE
          NonKeyAttributes:
            - sendAt
            - status
            - channelDeliveredAt
      - IndexName: ${self:service.name}-UserMessageBySendAt
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sendAt
            KeyType: RANGE
        Projection:
          ProjectionType: INCLUDE
          NonKeyAttributes:
            - channelMessageId
    GlobalSecondaryIndexes:
      - IndexName: ${self:service.name}-UserMessageByStatus
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: status
            KeyType: RANGE
        Projection:
          ProjectionType: INCLUDE
          NonKeyAttributes:
            - channelMessageId

userMessagesPendingTable:
  Type: AWS::DynamoDB::Table
  DeletionPolicy: Retain
  Properties:
    TableName: ${self:service.name}-UserMessagesPending
    AttributeDefinitions:
      - AttributeName: status
        AttributeType: S
      - AttributeName: messageChannelUser
        AttributeType: S
      - AttributeName: updatedAtMessageId
        AttributeType: S
    KeySchema:
      - AttributeName: status
        KeyType: HASH
      - AttributeName: messageChannelUser
        KeyType: RANGE
    BillingMode: PAY_PER_REQUEST
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    LocalSecondaryIndexes:
      - IndexName: ${self:service.name}-UserMessagePendingUpdatedAt
        KeySchema:
          - AttributeName: status
            KeyType: HASH
          - AttributeName: updatedAtMessageId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL

staticBucket:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    AccessControl: PublicRead
    BucketName: ${self:service.name}-static

dataTransferBucket:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    AccessControl: Private
    BucketName: ${self:service.name}-data-transfer
    PublicAccessBlockConfiguration:
      BlockPublicAcls: TRUE
      BlockPublicPolicy: TRUE
      IgnorePublicAcls: TRUE
      RestrictPublicBuckets: TRUE
    VersioningConfiguration:
      Status: Enabled

apiCloudFront:
  Type: AWS::CloudFront::Distribution
  DeletionPolicy: Retain
  Properties:
    DistributionConfig:
      Aliases:
        - ${file(./src/serverless.js):developerPrefix}${env:AWS_CLOUDFRONT_ALIAS} # optionally apply a developer prefix (<opt:developer>-) to the alias if command option provided
      Comment: OSU DX Multi-Channel Messaging API Distribution
      CustomErrorResponses:
        - ErrorCachingMinTTL: 60
          ErrorCode: 500
      DefaultCacheBehavior:
        AllowedMethods:
          - HEAD
          - GET
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
        CachedMethods:
          - HEAD
          - GET
        Compress: false
        MinTTL: 0
        DefaultTTL: 60
        MaxTTL: 3153600
        ForwardedValues:
          Cookies:
            Forward: all
          Headers:
            - Authorization
            - x-api-key
          QueryString: true
        TargetOriginId: ${self:service.name}-cloudfront
        ViewerProtocolPolicy: https-only
      Enabled: true
      HttpVersion: http2
      Origins:
        - Id: ${self:service.name}-cloudfront
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
            OriginSSLProtocols:
              - TLSv1.2
          DomainName:
            !Join [
              '',
              [!Ref ApiGatewayRestApi, '.execute-api.${self:provider.region}.amazonaws.com'],
            ]
          OriginPath: '/${self:provider.stage}'
      PriceClass: PriceClass_All
      ViewerCertificate:
        AcmCertificateArn: ${env:AWS_CLOUDFRONT_CERT_ARN}
        MinimumProtocolVersion: TLSv1
        SslSupportMethod: sni-only
