Resources:
  apiSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:service.name}-api
  messagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${opt:stage, self:provider.stage}-dx-mcm-Messages
      AttributeDefinitions:
        - AttributeName: sendAt
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: sendAt
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
