Resources:
  apiSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:service.name}-api
  messagesSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service.name}-messages.fifo
      ContentBasedDeduplication: true
      FifoQueue: true
  messagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${opt:stage, self:provider.stage}-dx-mcm-Messages
      AttributeDefinitions:
        - AttributeName: sendAt
          AttributeType: S
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: sendAt
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: ${opt:stage, self:provider.stage}-dx-mcm-MessageStatuses
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: sendAt
              KeyType: RANGE
          Projection:
            NonKeyAttributes:
              - id
            ProjectionType: INCLUDE
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
  staticBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: osu-dx-mcm-static
      AccessControl: PublicRead
