staticBucket:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    AccessControl: PublicRead
    BucketName: ${self:service.name}-static

dataTransferBucket:
  Type: AWS::S3::Bucket
  DeletionPolicy: Retain
  Properties:
    AccessControl: Private
    BucketName: ${self:service.name}-data-transfer
    PublicAccessBlockConfiguration:
      BlockPublicAcls: TRUE
      BlockPublicPolicy: TRUE
      IgnorePublicAcls: TRUE
      RestrictPublicBuckets: TRUE
    VersioningConfiguration:
      Status: Enabled

apiCloudFront:
  Type: AWS::CloudFront::Distribution
  DeletionPolicy: Retain
  Properties:
    DistributionConfig:
      Aliases:
        - ${file(./src/serverless.js):developerPrefix}${env:AWS_CLOUDFRONT_ALIAS} # optionally apply a developer prefix (<opt:developer>-) to the alias if command option provided
      Comment: OSU DX Multi-Channel Messaging API Distribution
      CustomErrorResponses:
        - ErrorCachingMinTTL: 60
          ErrorCode: 500
      DefaultCacheBehavior:
        AllowedMethods:
          - HEAD
          - GET
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
        CachedMethods:
          - HEAD
          - GET
        Compress: false
        MinTTL: 0
        DefaultTTL: 60
        MaxTTL: 3153600
        ForwardedValues:
          Cookies:
            Forward: all
          Headers:
            - Authorization
            - x-api-key
          QueryString: true
        TargetOriginId: ${self:service.name}-cloudfront
        ViewerProtocolPolicy: https-only
      Enabled: true
      HttpVersion: http2
      Origins:
        - Id: ${self:service.name}-cloudfront
          CustomOriginConfig:
            OriginProtocolPolicy: https-only
            OriginSSLProtocols:
              - TLSv1.2
          DomainName:
            !Join [
              '',
              [!Ref ApiGatewayRestApi, '.execute-api.${self:provider.region}.amazonaws.com'],
            ]
          OriginPath: '/${self:provider.stage}'
      PriceClass: PriceClass_All
      ViewerCertificate:
        AcmCertificateArn: ${env:AWS_CLOUDFRONT_CERT_ARN}
        MinimumProtocolVersion: TLSv1
        SslSupportMethod: sni-only
