userMessagesSqsQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service.name}-user-messages

userMessageErrorsSqsQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service.name}-user-message-errors

userMessageStateMachineLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: ${self:service.name}-userMessageStateMachineLogGroup
    RetentionInDays: 14
