messagesSqsQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-messages.fifo
    ContentBasedDeduplication: true
    FifoQueue: true

messageErrorsSqsQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: ${self:service}-message-errors

messageStateMachineLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: ${self:service}-messageStateMachineLogGroup
    RetentionInDays: 14
