require('./config');

const DYNAMODB_API_VERSION = '2012-08-10';
const DYNAMODB_TABLE_PREFIX = `${process.env.SERVICE_NAME}`;
const DYNAMODB_REGION = process.env.DYNAMODB_REGION || 'us-west-2';
const ENV = `${process.env.ENV}`;
const MESSAGE_STATE_MACHINE_ARN = `${process.env.MESSAGE_STATE_MACHINE_ARN}`;
const SQS_ERROR_MESSAGE_QUEUE_NAME = `${process.env.SQS_ERROR_MESSAGE_QUEUE_NAME}`;
const SQS_ERROR_USER_MESSAGE_QUEUE_NAME = `${process.env.SQS_ERROR_USER_MESSAGE_QUEUE_NAME}`;
const SQS_PROCESS_MESSAGE_QUEUE_NAME = `${process.env.SQS_PROCESS_MESSAGE_QUEUE_NAME}`;
const SQS_PROCESS_USER_MESSAGE_QUEUE_NAME = `${process.env.SQS_PROCESS_USER_MESSAGE_QUEUE_NAME}`;
const USER_MESSAGE_STATE_MACHINE_ARN = `${process.env.USER_MESSAGE_STATE_MACHINE_ARN}`;

export {
  DYNAMODB_API_VERSION,
  DYNAMODB_TABLE_PREFIX,
  DYNAMODB_REGION,
  ENV,
  MESSAGE_STATE_MACHINE_ARN,
  SQS_ERROR_MESSAGE_QUEUE_NAME,
  SQS_ERROR_USER_MESSAGE_QUEUE_NAME,
  SQS_PROCESS_MESSAGE_QUEUE_NAME,
  SQS_PROCESS_USER_MESSAGE_QUEUE_NAME,
  USER_MESSAGE_STATE_MACHINE_ARN,
};
