require('./config');

const DYNAMODB_API_VERSION = '2012-08-10';
const DYNAMODB_TABLE_PREFIX = `${process.env.SERVICE_NAME}`;
const MESSAGE_STATE_MACHINE_ARN = `${process.env.MESSAGE_STATE_MACHINE_ARN}`;
const SNS_TOPIC_ARN = `${process.env.SNS_TOPIC_ARN}`;
const SQS_PROCESS_MESSAGE_QUEUE_NAME = `${process.env.SQS_PROCESS_MESSAGE_QUEUE_NAME}`;
const SQS_PROCESS_USER_MESSAGE_QUEUE_NAME = `${process.env.SQS_PROCESS_USER_MESSAGE_QUEUE_NAME}`;

export {
  DYNAMODB_API_VERSION,
  DYNAMODB_TABLE_PREFIX,
  MESSAGE_STATE_MACHINE_ARN,
  SNS_TOPIC_ARN,
  SQS_PROCESS_MESSAGE_QUEUE_NAME,
  SQS_PROCESS_USER_MESSAGE_QUEUE_NAME,
};
